### ISSUE TITLE
React Native Authentication (OIDC) SDK for IS & Samples

### ISSUE THREAD

**Issue by Abira16** [asgardeo/asgardeo-react-native-oidc-sdk#4]
**Problem description**

As of now, Identity Server doesn't have any client-side tools like SDKs or official guides on how to integrate react native application with IS.

Having official SDKs, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on.
1. Selecting and applying best practices on different authentication protocols
2. Selecting correct libraries to implement
3. Make that client-side implementation to integrated with IS

**Preferred Solution**
Have React Native SDK, sample, and needed guides to integrate the application with Identity Server.

Effort FE::119

**Tasks**

- [ ] [React Native Authentication (OIDC) SDK Development](https://github.com/asgardio/asgardio-react-native-oidc-sdk/issues/5)

- [ ] Developer Documentation for React Native SDK

- [ ] Sample App Development & Demonstration 

- [ ] Testing with using React Native Testing Library

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
