### ISSUE TITLE
React Native Authentication (OIDC) SDK Development 

### ISSUE THREAD

**Issue by Abira16** [asgardeo/asgardeo-react-native-oidc-sdk#5]
**Description**

As of now, Identity Server doesn't have any client-side tools like SDKs or official guides on how to integrate react native application with IS. #4 

**Description of the solution you would prefer**

Develop a fully fledge React Native Authentication (ODC) SDK to provide secure authentication for React Native application with IS.

**Task**

- [ ] [Creating Infrastructure  for RN SDK](https://github.com/asgardio/asgardio-react-native-oidc-sdk/issues/7)

- [ ] Adding Sign In Sign out Functionalities to the RN SDK

- [ ] Add Extracting User Information Functionalities to RN app

- [ ] Testing for SDK

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
