### ISSUE TITLE
Create Infrastructure for RN SDK

### ISSUE THREAD

**Issue by Abira16** [asgardeo/asgardeo-react-native-oidc-sdk#7]
**Description**
Setting up initial project skeleton for the SDK and samples, generated with [[React Native CLI using Typescript] ](https://reactnative.dev/docs/typescript)

**Task**

- [x] [Create the workspace for SDK](https://github.com/asgardio/asgardio-react-native-oidc-sdk/pull/8)

- [x] [Create a sample app folder for basic usage](https://github.com/asgardio/asgardio-react-native-oidc-sdk/pull/8)

- [x] Initialize README file sketches for the SDK and the Sample

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
